
"editor look
set number
set ruler
set wrap
syntax on

"theme
set t_Co=256
colorscheme molokai

"file format
set encoding=utf-8
set fileencoding=utf-8
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set ambiwidth=double

"search
set incsearch
set hlsearch
set smartcase

"editing
set autoindent
set backspace=2 "make backspace work like most other apps
set mouse=a
set pastetoggle=<F2> "use F2 to toggle paste mode

"white space
set list
set lcs=tab:\|_,trail:~

"smarty
let smarty_left_delimiter='{%'
let smarty_right_delimiter='%}'

"file type
au BufRead,BufNewFile *.tpl set filetype=html
au BufRead,BufNewFile *.json set filetype=javascript

"zencoding
let g:user_emmet_leader_key='<C-e>'

"plugin
filetype plugin indent on

"markdown
let g:vim_markdown_folding_disabled=1

"syntax checking
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_javascript_eslint_exec = 'eslint'

"airline
set laststatus=2
let g:airline_powerline_fonts = 1
