
"editor look
set number
set ruler
set wrap
syntax on

"theme
set t_Co=256
colorscheme molokai

"file format
set encoding=utf-8
set fileencoding=utf-8
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set ambiwidth=double

"search
set incsearch
set hlsearch
set smartcase

"editing
set autoindent
set backspace=2 "make backspace work like most other apps
set mouse=a
set pastetoggle=<F2> "use F2 to toggle paste mode

"white space
set list
set lcs=tab:\|_,trail:~

"smarty
let smarty_left_delimiter='{%'
let smarty_right_delimiter='%}'

"file type
au BufRead,BufNewFile *.tpl set filetype=html
au BufRead,BufNewFile *.json set filetype=javascript

"zencoding
let g:user_zen_settings = {
\ 	'smarty': {
\ 		'extends': 'html'
\ 	}
\}
let g:user_zen_expandabbr_key='<C-e>'

"plugin
filetype plugin indent on

"markdown
let g:vim_markdown_folding_disabled=1

"jshint
let jshint2_save=1

"airline
set laststatus=2
let g:airline_powerline_fonts = 1
