# .bash_profile

# Get the aliases and functions

# User specific environment and startup programs
export PATH=$PATH:$HOME/bin:$HOME/Library/Android/sdk/platform-tools
export ANDROID_HOME=$HOME/Library/Android/sdk
export LANG=zh_CN.utf8
export PATH
export SVN_EDITOR=vim
alias grep='grep --color'
alias tailf='tail -f'
alias x5='python ~/x5-inspector/inspector.py  --adb /usr/local/bin/adb'
alias md5sum='md5'

